### ISSUE TITLE
Production use?

### ISSUE THREAD

**Issue by BatteryAcid** [sinha-abhishek/janus-dynamodb#1]
Hello, nice work!  Have you used this in production?

thanks

**Comment by sinha-abhishek** [comment]
Yes, we are using this image with Amazon ECS service, though we haven't yet used this on large scale. Would be happy to help in case of any issues

**Comment by BatteryAcid** [comment]
Thanks for the response.  I plan on getting the JanusGraph stuff deployed to ECS this week, so this should help.  thanks!
