### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by BatteryAcid** [sinha-abhishek/janus-dynamodb#3]
Hello!

Our performance seems very slow with read operations over various sized datasets.  We've played around with various configurations through Janus-dynamodb, TinkerPop, and Gremlin without much luck.  Are you able to achieve good performance with your setup?  If so would you kindly post the configurations you've successfully used?

thanks!

**Comment by sinha-abhishek** [comment]
Play around with the following parameters
storage.buffer-size
cache.db-cache
ids.block-size
query.batch
query.fast-property
storage.batch-loading
storage.dynamodb.enable-parallel-scan
storage.dynamodb.client.connection-max
storage.dynamodb.client.executor.max-concurrent-operations

Also performance depends on your indexes and whether or not the queries you are running are optimized. Like I faced a similar issue with loading more than 400 vertexes in one json query and adding edges from on vertex. I was making a mistake of creating a vertex and immediately adding a edge from required vertex and doing same in one loop. I changed the query slightly to do following : 

- Add all the vertices with their properties to the graph (but no edges). Maintain a map from vertex id to JanusGraph’s internal vertex id (i.e. vertex.getId()) which is a 64 bit long id.
- Add all the edges using the map to look-up JanusGraph’s vertex id and retrieving the vertices using that id. This improved performance by reducing the query time by half. Similar small optimizations have helped.

**Comment by monali01** [comment]
I have played around with all the properties you listed above but my read queries (specially the repeat()) are really slow. I have composite graph index but I am not sure if they were created and applied on Dynamodb and that could be the reason for poor performance. Have you noticed any problems like that?

**Comment by sinha-abhishek** [comment]
I am hoping awslabs guys can answer this. Composite indexes do work fine for me. Maybe, in your dev environment, you can try setting `query.force-index` to true and see if your queries run fine to check if your indexes are proper. 
repeat() performance I have not really tested out as for our setup there were not much need for such searches. Maybe try around with setting scan-limit and read-capacity if these work.

**Comment by sinha-abhishek** [comment]
Closing this as issue is not related to container but with awslabs project
